export const GET_USER_AUTH = "GET_USER_AUTH";
export const SIGN_IN = "SIGN_IN";

export const GET_ROADMAP_SUCCESS = "GET_ROADMAP_SUCCESS";
export const GET_ROADMAP_FAILURE = "GET_ROADMAP_FAILURE";
export const CREATE_ROADMAP_SUCCESS = "CREATE_ROADMAP_SUCCESS";
export const CREATE_ROADMAP_FAILURE = "CREATE_ROADMAP_FAILURE";
export const EDIT_ROADMAP_SUCCESS = "EDIT_ROADMAP_SUCCESS";
export const EDIT_ROADMAP_FAILURE = "EDIT_ROADMAP_FAILURE";
