export const GET_USER_AUTH = "GET_USER_AUTH";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
