// user reducer actions
export const GET_USER_AUTH = "GET_USER_AUTH";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const GET_ROADMAP_SUCCESS = "GET_ROADMAP_SUCCESS";
export const GET_ROADMAP_FAILURE = "GET_ROADMAP_FAILURE";
export const CREATE_ROADMAP = "CREATE_ROADMAP";
export const EDIT_ROADMAP = "EDIT_ROADMAP";
export const RESET_ROADMAP = "RESET_ROADMAP";
export const DELETE_ROADMAP = "DELETE_ROADMAP";
