# Generated by Django 3.1.2 on 2020-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="liked_roadmaps",
            field=models.ManyToManyField(
                related_name="liked_roadmap_user", to="roadmap.Roadmap"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="my_roadmaps",
            field=models.ManyToManyField(
                related_name="my_roadmap_user", to="roadmap.Roadmap"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pinned_roadmaps",
            field=models.ManyToManyField(
                related_name="pinned_roadmap_user", to="roadmap.Roadmap"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_picture_url",
            field=models.CharField(default="", max_length=64),
        ),
    ]
