# Generated by Django 3.1.2 on 2020-11-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0003_auto_20201107_0353"),
        ("user", "0002_auto_20201106_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="liked_roadmaps",
            field=models.ManyToManyField(
                blank=True, related_name="liked_roadmap_user", to="roadmap.Roadmap"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="my_roadmaps",
            field=models.ManyToManyField(
                blank=True, related_name="my_roadmap_user", to="roadmap.Roadmap"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pinned_roadmaps",
            field=models.ManyToManyField(
                blank=True, related_name="pinned_roadmap_user", to="roadmap.Roadmap"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_picture_url",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
