# Generated by Django 3.1.2 on 2020-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0006_remove_roadmap_sections"),
        ("user", "0003_auto_20201107_0353"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="my_roadmaps",
        ),
        migrations.AlterField(
            model_name="user",
            name="liked_roadmaps",
            field=models.ManyToManyField(
                blank=True, related_name="liked_roadmaps_user", to="roadmap.Roadmap"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pinned_roadmaps",
            field=models.ManyToManyField(
                blank=True, related_name="pinned_roadmaps_user", to="roadmap.Roadmap"
            ),
        ),
    ]
