# Generated by Django 3.1.2 on 2020-11-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_auto_20201107_0353"),
        ("section", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="section", to="task.Task"
            ),
        ),
    ]
