# Generated by Django 3.1.2 on 2020-11-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0006_remove_roadmap_sections"),
        ("section", "0002_auto_20201107_0353"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="tasks",
        ),
        migrations.AddField(
            model_name="section",
            name="roadmap",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_roadmap",
                to="roadmap.roadmap",
            ),
        ),
    ]
