# Generated by Django 3.1.2 on 2020-11-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roadmap", "0001_initial"),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="roadmap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmap_comment",
                to="roadmap.roadmap",
            ),
        ),
    ]
