# Generated by Django 3.1.2 on 2020-11-07 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0002_auto_20201106_1634"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment", "0002_comment_roadmap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="comment",
            name="roadmap",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmap_comment",
                to="roadmap.roadmap",
            ),
        ),
    ]
