# Generated by Django 3.1.2 on 2020-11-06 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=64)),
                ("date", models.DateField()),
                ("level", models.IntegerField()),
                ("like_count", models.IntegerField()),
                ("comment_count", models.IntegerField()),
                ("pin_count", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_roadmap",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="originial_author_roadmap",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
