# Generated by Django 3.1.2 on 2020-11-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0003_auto_20201107_0353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmap",
            name="date",
            field=models.DateTimeField(blank=True),
        ),
    ]
