# Generated by Django 3.1.2 on 2020-11-08 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0004_auto_20201107_0652"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="progress",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
