# Generated by Django 3.1.2 on 2020-11-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0005_auto_20201108_1811"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roadmap",
            name="sections",
        ),
    ]
