# Generated by Django 3.1.2 on 2020-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0006_remove_roadmap_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmap",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
