# Generated by Django 3.1.2 on 2020-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='count_roadmap',
            field=models.IntegerField(default=0),
        ),
    ]
