# Generated by Django 3.1.2 on 2020-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=64)),
                ("url", models.TextField()),
                ("type", models.IntegerField()),
                ("description", models.TextField()),
                ("checked", models.BooleanField()),
                (
                    "roadmap",
                    models.ManyToManyField(
                        related_name="task_roadmap", to="roadmap.Roadmap"
                    ),
                ),
            ],
        ),
    ]
