# Generated by Django 3.1.2 on 2020-11-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0003_auto_20201107_0353"),
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="roadmap",
            field=models.ManyToManyField(
                blank=True, related_name="task_roadmap", to="roadmap.Roadmap"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="url",
            field=models.TextField(blank=True),
        ),
    ]
