# Generated by Django 3.1.2 on 2020-11-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("section", "0003_auto_20201108_1838"),
        ("roadmap", "0006_remove_roadmap_sections"),
        ("task", "0002_auto_20201107_0353"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_section",
                to="section.section",
            ),
        ),
        migrations.RemoveField(
            model_name="task",
            name="roadmap",
        ),
        migrations.AddField(
            model_name="task",
            name="roadmap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_roadmap",
                to="roadmap.roadmap",
            ),
        ),
    ]
