# Generated by Django 3.1.2 on 2020-11-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_auto_20201108_1838"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="url",
            field=models.TextField(default=""),
        ),
    ]
